server:
  port: 8888

eureka:
  instance:
    hostname: config
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenchensheng/spring-boot-cloud
          search-paths: config-repo
    #        读取本地文件时采用以下配置
    #        native:
    #          search-locations: file:/config-repo
    #        bootstrap: true
    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: rabbitmq

  security:
    user:
      name: user
      password: ${CONFIG_SERVER_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh