spring:
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true

  rabbitmq:
    host: rabbitmq

  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

  zipkin:
    base-url: http://zipkin:9411 # 指定了 Zipkin 服务器的地址
    discoveryClientEnabled: true

server:
  port: 8070

msg: Hello


authserver:
  hostname: auth-service
  port: 5000
  contextPath: /uaa


security:
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current
    client:
      clientId: svcb-service
      clientSecret: ${spring.security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS