logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error

server:
  port: 8040


eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
  instance:
    # 表示eureka client发送心跳给server端的频率，默认为30秒
    leaseRenewalIntervalInSeconds: 10
    # 健康检查的地址（依赖spring-boot-starter-actuator）
    health-check-url-path: /actuator/health
    # 放入请求头，向此服务发送请求，访问此服务的 Actuator 开放的端点
    metadata-map:
      # These two are needed so that the server
      user.name: ${spring.security.user.name}
      # can access the protected client endpoints
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  security:
    user:
      name: admin
      password: ${MONITOR_SERVER_PASSWORD:admin}